include:
  - project: gitlab/pipeline-lib
    file: docker.yml
    ref: kaniko-0.4

stages:
  - setup
  - build

default:
  interruptible: true # allow to auto-cancel redundant pipelines
  tags:
    - amd64
    - cloud
    - linux

variables:
  DOCKER_IMAGE_NAME: ${CI_REGISTRY_IMAGE}/py310-poetry

publish_ci_image:
  stage: setup
  extends:
    - .deploy_docker
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event' && $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH
      changes:
        - Dockerfile

install_deps:
  stage: build
  image: ${DOCKER_IMAGE_NAME}:latest
  script:
    - poetry install
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event' && $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH
