stages:
  - build

install_deps:
  stage: build
  image: python:3.10.12-slim
  script:
    - poetry install
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event' && $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH
      when: always
