include:
  - project: gitlab/pipeline-lib
    file: docker.yml
    ref: kaniko-0.4

stages:
  - setup
  - build

default:
  interruptible: true # allow to auto-cancel redundant pipelines
  tags:
    - amd64
    - cloud
    - linux

variables:
  DOCKER_CONTEXT: $CI_PROJECT_DIR/
  DOCKER_TAG: latest
  DOCKERFILE: $CI_PROJECT_DIR/Dockerfile

publish_ci_image:
  stage: setup
  extends:
    - .deploy_docker
  rules:
    - changes:
        - $DOCKERFILE

.install_deps:
  stage: build
  image: python:3.10.12-slim
  script:
    - poetry install
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event' && $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH
      when: always
# build:
#   stage: build-image
#   extends:
#   - .build_docker
#   rules:
#     - changes:
#       - docker/**/* # all files under folder 'dockerfiles'
