[tool.poetry]
name = "lang-chain-qa"
version = "0.1.0"
description = ""
authors = ["grzenkom <marek.grzenkowicz@roche.com>"]
readme = "README.md"
packages = [{include = "lang_chain_qa", from = "src"}]

[tool.poetry.dependencies]
python = "^3.10"
langchain = "0.0.251"
huggingface-hub = "0.16.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
