[tool.poetry]
name = "lang-chain-qa"
version = "0.1.0"
description = ""
authors = ["grzenkom <marek.grzenkowicz@roche.com>"]
readme = "README.md"
packages = [{include = "lang_chain_qa", from = "src"}]

[tool.poetry.dependencies]
python = "^3.10"
# for a list of `llms` extras, see https://github.com/langchain-ai/langchain/blob/master/libs/langchain/pyproject.toml#L229
langchain = {version = "0.0.251", extras = ["llms"]} 


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
